from .htmlblock import HTMLBlock
from .htmlsection import HTMLSection
from .htmlintro import HTMLIntro
from .htmlcontact import HTMLContact
from .htmlhistory import HTMLHistory
from .htmlskills import HTMLSkills
from .htmleducation import HTMLEducation
from .htmlbody import HTMLBody
from .htmlhead import HTMLHead
from .htmlresume import HTMLResume
